# Generated by Django 4.0.1 on 2022-05-31 07:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_rename_user_createcustomer_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreateCustomer',
            new_name='Customer',
        ),
    ]
